Update scheduled_pipeline_job.yml

diff --git a/scripts/scheduled_pipeline_job.yml b/scripts/scheduled_pipeline_job.yml
--- a/scripts/scheduled_pipeline_job.yml
+++ b/scripts/scheduled_pipeline_job.yml
@@ -84,28 +84,28 @@ jobs:
 
   create_endpoint:
     command: | 
-      # Define the endpoint name
-      ENDPOINT_NAME="endpoint-eunsang"
+      # # Define the endpoint name
+      # ENDPOINT_NAME="endpoint-eunsang"
       
-      # Check if the endpoint already exists by capturing the exit code
-      az ml online-endpoint show --name $ENDPOINT_NAME \
-        --workspace-name inbrein-azure-ml-research-eunsang \
-        --resource-group inbrein-azure-ml-research > /dev/null 2>&1
+      # # Check if the endpoint already exists by capturing the exit code
+      # az ml online-endpoint show --name $ENDPOINT_NAME \
+      #   --workspace-name inbrein-azure-ml-research-eunsang \
+      #   --resource-group inbrein-azure-ml-research > /dev/null 2>&1
         
-      if [ $? -eq 0 ]; then
-        echo "Endpoint $ENDPOINT_NAME already exists. Updating existing endpoint."
-        az ml online-endpoint update \
-          -n $ENDPOINT_NAME \
-          -f /app/configs/automl_endpoint_settings.yml \
-          --workspace-name inbrein-azure-ml-research-eunsang \
-          --resource-group inbrein-azure-ml-research
-      else
+      # if [ $? -eq 0 ]; then
+      #   echo "Endpoint $ENDPOINT_NAME already exists. Updating existing endpoint."
+      #   az ml online-endpoint update \
+      #     -n $ENDPOINT_NAME \
+      #     -f /app/configs/automl_endpoint_settings.yml \
+      #     --workspace-name inbrein-azure-ml-research-eunsang \
+      #     --resource-group inbrein-azure-ml-research
+      # else
         echo "Endpoint $ENDPOINT_NAME does not exist. Creating new endpoint."
         az ml online-endpoint create \
           -f /app/configs/automl_endpoint_settings.yml \
           --workspace-name inbrein-azure-ml-research-eunsang \
           --resource-group inbrein-azure-ml-research
-      fi
+      # fi
 
       # Dummy output to ensure this job completes before the next
       echo "Endpoint operation completed" > ${{outputs.endpoint_trigger}}/endpoint_trigger.txt
