Update azure-ml-setup.yml

diff --git a/.github/workflows/azure-ml-setup.yml b/.github/workflows/azure-ml-setup.yml
--- a/.github/workflows/azure-ml-setup.yml
+++ b/.github/workflows/azure-ml-setup.yml
@@ -53,39 +53,39 @@ jobs:
         az extension add -n ml
         az ml -h 
 
-    - name: Sync keys for dependent resources
-      run: |
-        az ml workspace sync-keys \
-        --resource-group inbrein-azure-ml-research \
-        --name inbrein-azure-ml-research-eunsang
+    # - name: Sync keys for dependent resources
+    #   run: |
+    #     az ml workspace sync-keys \
+    #     --resource-group inbrein-azure-ml-research \
+    #     --name inbrein-azure-ml-research-eunsang
 
-    - name: Configure workspace permission to use managed identity
-      run: |
-        # Get the ACR instance name
-        acr_instance_name=$(az ml workspace show \
-          --name inbrein-azure-ml-research-eunsang \
-          --resource-group inbrein-azure-ml-research \
-          --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
-          --query container_registry \
-          -o tsv)
+    # - name: Configure workspace permission to use managed identity
+    #   run: |
+    #     # Get the ACR instance name
+    #     acr_instance_name=$(az ml workspace show \
+    #       --name inbrein-azure-ml-research-eunsang \
+    #       --resource-group inbrein-azure-ml-research \
+    #       --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
+    #       --query container_registry \
+    #       -o tsv)
     
-        # Check if the ACR instance name was found
-        if [ -z "$acr_instance_name" ]; then
-          echo "ACR instance name not found."
-          exit 1
-        fi
+    #     # Check if the ACR instance name was found
+    #     if [ -z "$acr_instance_name" ]; then
+    #       echo "ACR instance name not found."
+    #       exit 1
+    #     fi
     
-        # Set the environment variable
-        echo "ACR_INSTANCE_NAME=$(basename $acr_instance_name)" >> $GITHUB_ENV
+    #     # Set the environment variable
+    #     echo "ACR_INSTANCE_NAME=$(basename $acr_instance_name)" >> $GITHUB_ENV
     
-        # Disable admin user to use managed identity
-        az acr update --name $(basename $acr_instance_name) --admin-enabled false
+    #     # Disable admin user to use managed identity
+    #     az acr update --name $(basename $acr_instance_name) --admin-enabled false
     
-    - name: Create Azure ML Compute Cluster 
-      run: | 
-        az ml compute create --file ./scripts/create_compute_cluster.yml \
-        --resource-group inbrein-azure-ml-research \
-        --workspace-name inbrein-azure-ml-research-eunsang
+    # - name: Create Azure ML Compute Cluster 
+    #   run: | 
+    #     az ml compute create --file ./scripts/create_compute_cluster.yml \
+    #     --resource-group inbrein-azure-ml-research \
+    #     --workspace-name inbrein-azure-ml-research-eunsang
         
     - name: Create Azure ML Schedule
       run: |
